# Generated by Django 4.1.2 on 2022-11-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('position', models.CharField(choices=[('member', 'member'), ('developer', 'developer'), ('instructor', 'instructor')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
